### PR TITLE
add palindromeChecker problem

### PR DESCRIPTION
**Pull request by nsluss**

### CODE REVIEW

**Comment by nsluss** [comment]
Added sumOfSquares problem, recommend merging this request ASAP for maximal optimization of learning efficiency. :+1:

**Comment by jbobron** [comment]
Why has this not been merged yet? its ridiculous.

**Comment by pravipati** [comment]
this should be merged. :+1:

**Comment by atj1979** [comment]
image

**Comment by atj1979** [comment]
There are two kinds of people in this world.  Those who merge pull requests and those who pick their nose on public transit during rush hour.

**Comment by michelletrame** [comment]
i'd hella merge dat shit.

**Comment by cjnething** [comment]
We're all waiting for this to get merged. If this isn't merged, Xander will cry.

**Comment by sdwebster** [comment]
Nil: merge! Noah has "ah-ha" one, Gremlin!

**Comment by sunny-g** [comment]
These two problems will single-handedly prepare you for a job at Google. Just saying.

**Comment by ruanp** [comment]
How many geniuses does it take to get a simple, critical pull request merged? What's the hold up here?

**Pull request merged**
